### ISSUE TITLE
Detale niebieskiego paska

### ISSUE THREAD

**Issue by kamil-kielczewski** [PatrykJutrowski/NewProject#8]
W tym napisie ustawiłeś górny margines na 3px przez co jest źle w stosunku do projektu. Trzeba ustawić na zero. 

Druga sprawa - właściwość `font-width` trzeba ustawić na mniejszą (bo czcionka jest zbyt gruba ) - podobnie z tym menu po prawej stronie tego paska.

Ostatnia rzecz strzałka w prawo w tym napisie -  wytnij ją i wstaw jako obrazek . I podobnie strzałki w dół w menu.

![image](https://user-images.githubusercontent.com/15379981/180650147-8c9663fb-afae-4f79-81b8-944088cca3a4.png)

**Comment by PatrykJutrowski** [comment]
Przegladarka poprawnie wyświetla kod z PHP storm index.html, zaś przeglądarka odpalając ten sam kod w repository github'a wyswietla zupełnie inaczej.

**Comment by kamil-kielczewski** [comment]
To oznacza że to nie jest ten sam kod. 
Pokaż konkretnie jaki kod tu i tu jaki obraz generuje

**Comment by kamil-kielczewski** [comment]
ok - teraz pasek niebieski jest w miarę wystarczająco zbliżony do tego z projektu (wiadomo że zwykle 100% się nie da bo są np. różnice w renderowaniu czcionek między programem graficznym używanym przez grafika do stworzenia projektu a przeglądarką
