### ISSUE TITLE
Detale białego paska (pod niebieskim)

### ISSUE THREAD

**Issue by kamil-kielczewski** [PatrykJutrowski/NewProject#9]
Powinno być tak
![image](https://user-images.githubusercontent.com/15379981/180878016-ee1018b6-d2dc-4be5-acc3-12e7860bb74e.png)

A jest tak
![image](https://user-images.githubusercontent.com/15379981/180878273-2c29cde7-ba4a-4e27-8fc1-2fc2106d8770.png)

1. Wyraz community ma nieprawidłową czcionkę (font-family - nie powinno być Intern tylko ta druga)
2. Pod itemem "Tutorials" powinna być niebieska kreska
3. Za gruby font (font-weight) dla Tutorials i pozostalych itemów
4. brak trójkącika po. "Get involved"
5. położenie buttona "Sign up" jest lekko błędne

**Comment by kamil-kielczewski** [comment]
nie zrobione punkty: 1,2,3. 
Pkt 5 - button ma niewłaściwe rozmiary (font może się różnić - ale rozmiar buttona powinien być zachowany)

**Comment by kamil-kielczewski** [comment]
Button signup nie zgadza się z projektem. Oto projekt
![image](https://user-images.githubusercontent.com/15379981/181494101-296a36e8-00c7-440f-931a-e2c8195d7f48.png)

A oto stronka
![image](https://user-images.githubusercontent.com/15379981/181494186-4dcfc2cb-1957-4ef8-af0e-b9d9f37d07fd.png)

długość buttona się niezgadza o 3px

**Comment by PatrykJutrowski** [comment]
Przez przypadek zamknąłem

**Comment by kamil-kielczewski** [comment]
jest ok
